apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebsitefrontend
  labels:
    app: mywebsite_frnt
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mywebsite_frnt
  template:
    metadata:
      labels:
        app: mywebsite_frnt
    spec:
      containers:
      - name: mywebsitefrontend
        image: ksudhy/$BUILD_NUMBER
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: mywebsitefrontend
  labels:
    app: mywebsite_frnt
spec:
  type: NodePort
  selector:
    app: mywebsite_frnt
  ports:
    - name: http
      port: 80
      nodePort: 32478


